language: ruby
cache: bundler
dist: trusty
env:
  - "RAILS_VERSION=4.2.6"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.1.0"
rvm:
  - 2.5.3
  - 2.6.0
  - 2.7.2
  - jruby
before_install:
  - gem update bundler
matrix:
  fast_finish: true
