language: ruby
cache: bundler
dist: trusty
env:
  - "RAILS_VERSION=4.2.6"
  - "RAILS_VERSION=5.2.0"
rvm:
  - 2.2.7
  - 2.4.1
  - jruby
before_install:
  - gem update bundler
matrix:
  fast_finish: true
  allow_failures:
    - env: RAILS_VERSION=master
